// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

void onManualShadesChange();
void onManualControlChange();

int manualShades;
bool manualControl;

void initProperties(){

  ArduinoCloud.addProperty(manualShades, READWRITE, ON_CHANGE, onManualShadesChange);
  ArduinoCloud.addProperty(manualControl, READWRITE, ON_CHANGE, onManualControlChange);

}

////////////////////////////ATTENTION!!!////////////////////////////////
// ATTENTION: No device is currently associated to this Thing,        //
// hence the Connection Handler code could not be generated           //
// Please associate an existing or new device or manually create your //
// instance of Connection Handler                                     //
// Eg.                                                                // 
// WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);   //
////////////////////////////////////////////////////////////////////////

#error "No device is currently associated to this Thing, hence the Connection Handler code could not be generated"
